### ISSUE TITLE
Java.lang.verifyError

### ISSUE THREAD

**Issue by vijay559** [junit-team/junit4#1378]
A similar error has been seen by others who were using the roboelectric library when they try to access a file. Some suggested to use -noverify jvm argument in the build file to avoid verification in JVM. But I believe this is something the library has to address. 

Can you please let me know. 

   URL resource = getClass().getResource("/a.doc");
   File file = new File(resource.getFile()); ----- I am getting error at this line. 

java.lang.VerifyError: Expecting a stackmap frame at branch target 20
Exception Details:
  Location:
    com/xxxx/test/file/File.<init>(Ljava/lang/String;)V @16: ifeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2a2b b700 462a 01b5 000d b800 44b6 0045
    0x0000010: 9900 04b1 2abb 0005 592b b700 12b5 000d
    0x0000020: b1                                     

	at com.good.docs.util.UtilsTest.checkForSanctity(UtilsTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 255

**Comment by kcooney** [comment]
@vijay559 this might be a problem with your JVM or your libraries or something else. It might not be a problem that this community can help with. Have you considered asking on stackoverflow.com ?

**Comment by vijay559** [comment]
Actually after seeing your response, I removed the -noverify JVM flag and tried it again and it started to work. I did couple of changes after I Posted this issue. Not sure which resolved that issue.

**Comment by vijay559** [comment]
Closing the issue as it is no longer happening. It might be the FILE IO api that I was using that caused this issue.
