### ISSUE TITLE
A Exception for junit4.12 about org/hamcrest/SelfDescribing

### ISSUE THREAD

**Issue by forvoid** [junit-team/junit4#1429]
hello, guy!
why my use junit4.12.jar thows Exception org/hamcrest/SelfDescribing,no hamcrest ?
java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:36)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by marcphilipp** [comment]
You need to add the hamcrest-core JAR to the classpath as described here: https://github.com/junit-team/junit4/wiki/Download-and-Install

**Comment by forvoid** [comment]
think you ~  I have add this JAR  now .the application is complise. thinks for you answer again

**Comment by Mi-La** [comment]
From which version the hamcrest-core is needed? We have used junit-4.10 and we didn't need the hamcrest at all. Was it change in 4.11? What about some note about it in wiki / doc?

**Comment by kcooney** [comment]
@Mi-La see https://github.com/junit-team/junit4/blob/master/doc/ReleaseNotes4.11.md

**Comment by Mi-La** [comment]
@kcooney Thanks, I already checked it. It states that there was an upgrade to Hamcrest 1.3 and that JUnitMatchers are now deprecated. But it doesn't say explicitly that I cannot use JUnit without Hamcrest at all. It took me some time to find it out.

**Comment by kcooney** [comment]
@Mi-La see the section on Maveb artifacts

**Comment by Mi-La** [comment]
@kcooney Ok, I see. Unfortunately our old project still uses Ant, so I didn't care about the Maven part ;-). Thanks

**Comment by geekyouth** [comment]
https://www.cnblogs.com/anny0404/p/5275595.html
![image](https://user-images.githubusercontent.com/12899262/45198019-c84b0b80-b296-11e8-80e3-646ba48a57c2.png)
亲测有效
