### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by dariusgm** [junit-team/junit4#1430]
Given the following class: 

```
public class IsCustomer {
  private static final CompanyRepository repository = new CompanyRepository();

  public static boolean apply(String id) {
    Optional<Company> optional = repository.find(id);
    if (optional.isPresent()) {
      Company company = optional.get();
      return company.getIsCustomer();
    } else {
      return false;
    }
  }
```

and the corresponding test
```
  @Test
  public void testNotFound() {
    try {
      boolean result = IsCustomer.apply("1");
      Assert.assertFalse(result);
    } catch (Exception exception) {
      exception.printStackTrace();
    }
  }
```

This code results in a nullpointer exception inside of junit, as the surrounding code is static.
The stacktrace:

```
java.lang.NullPointerException
	at xxx.IsCustomer.apply(IsCustomer.java:21)
	at xxx.IsCustomerTest.testNotFound(IsCustomerTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)	
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec - in xxx.IsCustomerTest
```

without the catch, the test will fail. Seems like a concurrency problem, as when I use an other id in the test that do not exist, the test is stabile.

**Comment by kcooney** [comment]
@dariusgm that exception is thrown from your code, not JUnit. I suggest using a debugger.

**Comment by kcooney** [comment]
@dariusgm  One thing to point out: your tests for `IsCustomer` depend on the state of `CompanyRepository`, which can make your tests fragile. For instance, depending on the state of `CompanyRepository` your test could be testing an ID that doesn't correspond to a Company, or your test could be testing an ID that corresponds to a Company that isn't a customer. Future changes to the state of `CompanyRepository` can cause your test to fail, or worse, test something else.

I suggest rewriting as follows:

```
public class IsCustomer implements Predicate<String> {
  private final CompanyRepository repository;

  IsCustomer(CompanyRepository repository) {
    this.repository = repository;
  }

  @Override
  public boolean apply(String id) {
    Optional<Company> optional = repository.find(id);
    if (optional.isPresent()) {
      Company company = optional.get();
      return company.getIsCustomer();
    } else {
      return false;
    }
  }
}
```

If you can easily and quickly populate `CompanyRepository` with fake data, then your test would create an instance and pass it to the `IsCustomer` constructor. Otherwise, you could use a framework like Mockito to mock it.

To wire the dependencies together, you could use a dependency injection framework like Spring, Dagger or Guice
