### ISSUE TITLE
NPE when asserting classes that return null in toString

### ISSUE THREAD

**Issue by valterc** [junit-team/junit4#1453]
```
    public static class NotString
    {

        private Object data;

        public NotString(Object data)
        {
            this.data = data;
        }

        @Override
        public boolean equals(Object obj)
        {
            if (this == obj)
                return true;
            if (obj == null)
                return false;
            if (getClass() != obj.getClass())
                return false;
            NotString other = (NotString) obj;
            if (this.data == null)
            {
                if (other.data != null)
                    return false;
            }
            else if (!this.data.equals(other.data))
                return false;
            return true;
        }

        @Override
        public String toString()
        {
            return null;
        }

    }

    @Test
    public void testNotStringClass()
    {
        assertEquals(new NotString(1), new NotString(2));
    }
```

This code results in a NPE from JUnit because the ToString method of the class is returning null.

Tested in JUnit 4.12

**Comment by marcphilipp** [comment]
On the one hand, IMHO `toString()` shouldn't ever return `null`. On the other hand, JUnit should not throw an NPE if it does.

@valterc Can you please post the relevant part of the stack trace?

**Comment by valterc** [comment]
@marcphilipp I agree with your points, but when working with third parties that is something we cannot change easily. 

I see you committed a fix, but here goes the trace anyway:

```
java.lang.NullPointerException
	at org.junit.Assert.format(Assert.java:844)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at test.testNotStringClass(test.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
