### ISSUE TITLE
junit-4.10 与amino-cbbs-0.3.1 的报错

### ISSUE THREAD

**Issue by navy-king** [junit-team/junit4#1534]
当使用amino的MasterWorker时报以下错误。但是在main里运行没有报错
java.lang.AssertionError
	at org.amino.pattern.internal.AbstractMasterWorker$WorkerPool.complete(Unknown Source)
	at org.amino.pattern.internal.DynamicMasterWorker$WorkWrapper.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kcooney** [comment]
The stack trace doesn't look related. If you think this is related to JUnit, we need more details. See https://stackoverflow.com/help/mcve for what details can be useful.

Note the current version of JUnit is 4.12
