### ISSUE TITLE
Exceptions thrown by Exception.getMessage() method cancel tests without failing the test

### ISSUE THREAD

**Issue by Nightara** [junit-team/junit4#1549]
Setup:
Create a new runtime exception that throws an Exception (E.g. NullPointer) within the getMessage() method.
Create a simple JUnit test (Without declaring expected exceptions) that throws this exception.

Expected Outcome: The test should fail and show a stack trace (Either of the underlying exception or the NullPointerException thrown)

Actual Outcome: The test is canceled silently and succeeds.

**Comment by bhegmanns** [comment]
Are you sure?

I wrote this classes:
public class TestFailsByExceptionThrowingAnExceptionInGetMessageTest {

    @Test
    public void exceptionInGetMessageMakeTheTestFails() {
        throw new MyException();
    }
}

/**
 * A new exception in this test.
 * 
 *
 */
class MyException extends RuntimeException{

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    @Override
    public String getMessage() {
        throw new NullPointerException("sorry");
    }
    
}

and the test fails with this stack trace:
java.lang.NullPointerException: sorry
	at org.junit.tests.assertion.MyException.getMessage(TestFailsByExceptionThrowingAnExceptionInGetMessageTest.java:28)
	at java.lang.Throwable.getLocalizedMessage(Throwable.java:391)
	at java.lang.Throwable.toString(Throwable.java:480)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:695)
	at java.lang.Throwable.printStackTrace(Throwable.java:667)
	at java.lang.Throwable.printStackTrace(Throwable.java:721)
	at org.junit.internal.Throwables.getStacktrace(Throwables.java:63)
	at org.junit.runner.notification.Failure.getTrace(Failure.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestListener.testFailure(JUnit4TestListener.java:91)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestListener.testFailure(JUnit4TestListener.java:69)
	at org.junit.runner.notification.SynchronizedRunListener.testFailure(SynchronizedRunListener.java:94)
	at org.junit.runner.notification.RunNotifier$6.notifyListener(RunNotifier.java:177)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:180)
	at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:167)
	at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:23)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:353)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:314)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:312)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:396)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

It look like your expected outcome.

**Comment by stefanbirkner** [comment]
I can confirm @bhegmanns result. @Nightara can you provide us an example and tell us how you execute your test.

**Comment by stefanbirkner** [comment]
That would be nice. Thank you.

**Comment by Nightara** [comment]
My setup:
NetBeans 8.2
OpenJDK 8 (1.8.0_181)
Maven 3.0.5_17
JUnit 4.12

I've uploaded my dummy Maven project (POM and source files) to [MavenJUnitTest.zip](https://github.com/junit-team/junit4/files/2501145/MavenJUnitTest.zip).
The project contains one test, the mentioned Exception and a dummy class throwing the Exception.

Executing the Maven Goal surefire:test on the demo project results in the following output:
`Running MyTest
This comes before the exception, so it should show up in the console
This object should throw an exception and fail the test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 sec`

**Comment by stefanbirkner** [comment]
I get a different result when I run

    mvn test

The result is

    Running MyTest
    This comes before the exception, so it should show up in the console
    This object should throw an exception and fail the test
    Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.07 sec <<< FAILURE!

This is exactly what I expect for this test. I'm running the test with Maven 3.5.0 and Oracle JDK 10.0.2. 

Can you run `mvn clean test` from the command-line and tell us what your output looks like.

I don't think that this is a JUnit bug. I think it is a bug in one of the tools or its configuration.

**Comment by stefanbirkner** [comment]
You're welcome. I'm happy to hear that your problem is solved.
