### ISSUE TITLE
Exception running JUnit4 tests

### ISSUE THREAD

**Issue by hellboy81** [junit-team/junit4#1573]
`jre 1.8.0_121`:

```java 
java.lang.ClassFormatError: Unknown constant tag 114 in class file org/junit/internal/builders/AllDefaultPossibilitiesBuilder
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:86)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:73)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:522)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by marcphilipp** [comment]
Which version of JUnit are you using?

**Comment by hellboy81** [comment]
Issue updated.

**Comment by marcphilipp** [comment]
Thanks! Could you share a sample project?

**Comment by marcphilipp** [comment]
Did you change anything on your end? JUnit 4.12 (and 4.13) should work with Java 8.

**Comment by hellboy81** [comment]
The problem solved after upgrading to `4.13-beta-1`.
