### ISSUE TITLE
why java.lang.NoSuchMethodError: org.hamcrest.core.AllOf.allOf(Lorg/hamcrest/Matcher;Lorg/hamcrest/Matcher;)Lorg/hamcrest/Matcher;

### ISSUE THREAD

**Issue by jhwsx** [junit-team/junit4#1579]
- dependencies
testCompile "junit:junit:$rootProject.ext.junitVersion"
testCompile "org.hamcrest:hamcrest-all:$rootProject.ext.hamcrestVersion"
junitVersion = '4.12'
hamcrestVersion = '1.3'

- error
```text
java.lang.NoSuchMethodError: org.hamcrest.core.AllOf.allOf(Lorg/hamcrest/Matcher;Lorg/hamcrest/Matcher;)Lorg/hamcrest/Matcher;

	at org.hamcrest.Matchers.allOf(Matchers.java:33)
	at com.example.android.architecture.blueprints.todoapp.test.AssertTests.testAssertThatHamcrestCoreMatchers(AssertTests.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```
- code 
```java
import org.hamcrest.Matchers;
import org.junit.Assert;
import org.junit.Test;

import java.util.Arrays;

public class AssertTests {
    @Test
    public void testAssertThatHamcrestCoreMatchers() {
        Assert.assertThat("good", Matchers.allOf(Matchers.equalTo("good"), Matchers.startsWith("good")));
    }
   
}
```
I have surfed the Internet for this problem for hours, and now I am very frustrated. I really want to solve this problem. Please give me a hand.

**Comment by kcooney** [comment]
This is related to Hamcrest, not JUnit.

I suggest asking on stackoverflow.com. See https://stackoverflow.com/help/how-to-ask

**Comment by jhwsx** [comment]
ok, thank you.
I have solved this problem by changing hamcrestVersion from 1.3 to 1.1.

**Comment by kcooney** [comment]
JUnit 4.12 requires Hamcrest 1.3, so your solution may lead to other problems.

My guess is one version of Hamcrest is being used at compile time and a different version (or multiple versions) is on the runtime runtime classpath. Alternatively you were missing one of the Hamcrest 1.3 jars.

If that doesn't help, please ask on stackoverflow.com and add a link to the question here
