### ISSUE TITLE
4.13-beta-1 causes java.lang.VerifyError: class com.intellij.junit4.JUnit4TestRunnerUtil

### ISSUE THREAD

**Issue by damianszczepanik** [junit-team/junit4#1582]
When running tests for https://github.com/damianszczepanik/cucumber-reporting/pull/801 with IntelliJ IDEA 2016.3.5 and 4.13-beta-1 I get the following:

```
Exception in thread "main" java.lang.VerifyError: class com.intellij.junit4.JUnit4TestRunnerUtil$5 overrides final method getRunner.()Lorg/junit/runner/Runner;
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:46)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1
Empty test suite.
```

Moving back to 4.12 solves the problem as mentioned in https://stackoverflow.com/questions/53512970/java-lang-verifyerror-class-com-intellij-junit4-junit4testrunnerutil5-override

**Comment by kcooney** [comment]
Looks like this was fixed in IntelliJ:

https://github.com/JetBrains/intellij-community/commit/5d3f4634cdd34ab74d68fa0f9b52a466a7e89453#diff-eac4f3b47c9783fd77f87e5947cc23a7

Not sure what release(s) contain that fix.

The plugin was extending org.junit.internal.requests.ClassRequest which is an internal class.

**Comment by marcphilipp** [comment]
> IntelliJ IDEA 2016.3.5

That's quite old. Have you tried a recent version?

**Comment by damianszczepanik** [comment]
Closing as it works with maven you are right - this is IDEA issue
